apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: gitleaks-scan
  namespace: tekton-pipelines
spec:
  workspaces:
    - name: source
  steps:
    - name: scan
      image: zricethezav/gitleaks:latest
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        gitleaks detect --source . --no-git -v
