apiVersion: apps/v1
kind: Deployment
metadata:
  name: voyage-matcher
  namespace: voyage

spec:
  replicas: 2

  selector:
    matchLabels:
      app: voyage-matcher

  template:
    metadata:
      labels:
        app: voyage-matcher

      annotations:
        # Prometheus scraping
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"

    spec:
      containers:
        - name: voyage-matcher

          image: docker.io/edaraanand/voyage:06f10e3ecc0c4f3b6c27950ca33a656352e789c1
          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          env:
            - name: CLICKHOUSE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: clickhouse-secret
                  key: CLICKHOUSE_USERNAME

            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clickhouse-secret
                  key: CLICKHOUSE_PASSWORD

          envFrom:
            - configMapRef:
                name: voyage-config

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"

            limits:
              cpu: "1"
              memory: "1Gi"

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 60
