apiVersion: v1
kind: Service
metadata:
  name: voyage-matcher
  namespace: voyage
spec:
  type: NodePort
  selector:
    app: voyage-matcher
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30303
