apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: voyage-listener
  namespace: tekton-pipelines
spec:
  serviceAccountName: voyage-trigger-sa
  triggers:
    - name: github-push-trigger
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: github-webhook-secret
                secretKey: secretToken
            - name: "eventTypes"
              value: ["push"]
      bindings:
        - ref: voyage-github-binding
      template:
        ref: voyage-trigger-template
