apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: voyage-github-binding
  namespace: tekton-pipelines
spec:
  params:
    - name: repo-url
      value: $(body.repository.clone_url)
    - name: revision
      value: $(body.after)   # commit SHA of the push, more precise than branch name
